# Deploy to Mythall-dev project using dev build commands to ensure we use the development enviroment and database

name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - dev
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm i
      - run: npm run build-dev
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_MYTHALL_DEV }}"
          channelId: live
          projectId: mythall-dev
          target: mythall
